server {
    listen 8080;
    server_name _;

    access_log /dev/stdout;
    error_log /dev/stderr warn;

    root /home/site/wwwroot/public;
    index index.php index.html;
    add_header X-App-Custom-Nginx "true" always;

    location ^~ /build/ {
        try_files $uri =404;
        expires 1y;
        add_header Cache-Control "public, immutable" always;
    }

    location / {
        add_header Cache-Control "no-store, no-cache, must-revalidate, max-age=0" always;
        add_header Pragma "no-cache" always;
        add_header Expires "Thu, 01 Jan 1970 00:00:00 GMT" always;
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        include /etc/nginx/fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param HTTP_CACHE_CONTROL "no-store, no-cache, must-revalidate, max-age=0";
    }
}
